export enum Routes {
  Login = '/login',
  Login_Start = '/login-start',
  Loading = '/loading',
  First_Login = '/first-login',
  Setup_Password = '/setup-password',
  Two_Fa_Login = '/2fa-login',
  Two_Fa_Setup = '/2fa-setup',
  Dashboard = '/dashboard',
  Products = '/products',
  Warehouses = '/warehouses',
  Stocks = '/stocks',
  Documents = '/documents',
  Reports = '/reports',
  Sales = '/sales',
  Users = '/users',
  Settings = '/settings',
}
